name: Deploy Face Recognition to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'Face Recognition/**'
      - '.github/workflows/deploy-face-recognition.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Change directory to subfolder
        run: cd 'Face Recognition'

      - name: Install dependencies
        run: |
          cd 'Face Recognition'
          pip install -r requirements.txt

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'leap-face-recognition-api'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: 'Face Recognition'
