name: Deploy site
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload site folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: Web_Development/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
